"""Change job data to date

Revision ID: 652dd683a62d
Revises: db47c99fd470
Create Date: 2023-04-03 15:02:00.885546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652dd683a62d'
down_revision = 'db47c99fd470'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('jobs', 'data')
    op.create_foreign_key(None, 'pets', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.add_column('jobs', sa.Column('data', sa.DATETIME(), nullable=True))
    op.drop_column('jobs', 'date')
    # ### end Alembic commands ###
