"""Add note to job

Revision ID: 80dae642d24d
Revises: 652dd683a62d
Create Date: 2023-04-03 15:08:24.596905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80dae642d24d'
down_revision = '652dd683a62d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('note', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pets', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.drop_column('jobs', 'note')
    # ### end Alembic commands ###
