"""add pets and owners table

Revision ID: 91ac356eee44
Revises: 45a2a30d39f2
Create Date: 2023-04-03 11:35:43.590893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ac356eee44'
down_revision = '45a2a30d39f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
